version: "3.3"

services:
  postgres:
    image: postgres:16
    ports:
      - 15432:5432
    volumes:
      - ./local/postgres/data/:/var/lib/postgresql/data
      - ./local/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: mypassword
  redis:
    image: redis:7.2.3
    ports:
      - 16379:6379
